export { default as PublicLayout } from "./PublicLayout" 
export { default as HomePages } from "./HomePages" 
export { default as About } from "./About" 
export { default as SoldProperty } from "./SoldProperty" 
export { default as News } from "./News" 
